version: "3.9"
services:
  postgres_db:
    image: postgres
    restart: always
    command: -p 5442
    env_file:
      - src/.env
    expose:
      - 5442
    ports:
      - "5442:5442"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis_db:
    image: redis
    restart: always
    expose:
      - 6389
    ports:
      - "6389:6389"
    volumes:
        - redis_data:/data
    entrypoint: redis-server --appendonly yes --port 6389


volumes:
  postgres_data:
  redis_data: 