version: "3.9"
services:
  nginx:
    image: nginx:latest
    ports:
      - "8001:80"
    volumes:
      - ./nginx/params.conf:/etc/nginx/proxy_params
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - staticfiles:/app/staticfiles/
    depends_on:
      - app
  app:
    depends_on:
      - postgres_db
    build:
      context: ./src
      dockerfile: Dockerfile
    image: eventchimp_be:v1
    environment:
      - PORT=8000
    env_file:
      - src/.env
    expose:
      - 8000
    command: sh -c "chmod +x /app/entrypoint.sh && sh /app/entrypoint.sh"
    volumes:
      - staticfiles:/app/staticfiles/
  postgres_db:
    image: postgres
    restart: always
    command: -p 5442
    env_file:
      - src/.env
    expose:
      - 5442
    ports:
      - "5442:5442"
    volumes:
      - postgres_data:/var/lib/postgresql/data/


volumes:
  postgres_data:
  staticfiles: