# Generated by Django 4.2 on 2024-01-11 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdateschedule',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_schedules', to='schedules.schedule'),
        ),
        migrations.AlterField(
            model_name='weekdayschedule',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekday_schedules', to='schedules.schedule'),
        ),
    ]
