# Generated by Django 4.2 on 2024-01-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='event',
            name='step_in_min',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='event',
            name='rolling_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
