# Generated by Django 4.2 on 2024-01-11 16:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_rename_updated_event_updated_at_event_step_in_min_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('organiser', 'title')},
        ),
    ]
