# Generated by Django 4.2 on 2024-01-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='step_in_min',
            new_name='step_in_minutes',
        ),
        migrations.AddField(
            model_name='event',
            name='min_notice_in_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
