# Generated by Django 4.2 on 2024-01-11 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_step_in_min_event_step_in_minutes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='min_notice_in_minutes',
            new_name='notice_in_minutes',
        ),
    ]
