# Generated by Django 4.2 on 2024-01-14 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_alter_customdateschedule_schedule_and_more'),
        ('events', '0006_rename_min_notice_in_minutes_event_notice_in_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.schedule'),
        ),
    ]
